#+options: toc:nil title:nil numbers:nil

=.Homework=

* NAME

Homework - Read and print the contents of files with options.

* SYNOPSIS

*Homework* [OPTIONS] [FILE...]

* DESCRIPTION

*Homework* reads the contents of the specified input file(s) and prints them to STDOUT. Each line can be reversed and a delay can be added between each line. If no files are provided, the program can read from the standard input (stdin).

* OPTIONS

- **-h, --help**: Display this help message.
- **-r, --reverse**: Reverse each line before printing.
- **-d DELAY, --delay DELAY**: Specify a delay in seconds or fractions thereof. Example: -d 0.5 for a 500 milliseconds delay.

* FILE

The name(s) of the file(s) to be processed. If no files are provided, the program will read from the standard input (stdin).

* RETURN VALUE

- 0 on success.
- 1 on failure.

* EXAMPLES

  - Homework -r -d 0.5 file1.txt file2.txt
    Read the contents of file1.txt and file2.txt, reverse each line, and print with a delay of 0.5 seconds between each line.

  - Homework -d 1.0 -r -h
    Display the help message.

  - cat file.txt | Homework -r -d 0.5
    Read the contents of file.txt from the standard input (stdin), reverse each line, and print with a delay of 0.5 seconds between each line.

* SEE ALSO

- [man(1)](https://linux.die.net/man/1/man)
- [cat(1)](https://linux.die.net/man/1/cat)
- [getopt(3)](https://linux.die.net/man/3/getopt)
- [usleep(3)](https://linux.die.net/man/3/usleep)
- [fopen(3)](https://linux.die.net/man/3/fopen)
