#+TITLE: Writers Strike Presentation


* Background Info

Began - May 2, 2023
Current Duration - Almost 5 months

Why?

- Ongoing labor dispute with /Alliance of Motion Picture and Television Producers/
- Originally began as just writers, has since spread to include actors as well (SAG-AFTRA strike)
- Residuals - similar to a royalty. Monetary gain from television/movie reruns, etc.
  Actors complain the producers share is reducing actors cut compared to a decade ago
- AI - Writers complain that they are seeing reduced work due to AI usage, and want AI implementation within the cinema field to remain a "tool" to assist with ideas or research, and not implemented to replace writers
  *Reword this point*


RIpple Effect?




* Script

Me:

Good morning
For the past few months, the Writers Guild of America has been on strike.
This might not seem like an issue, but it's ended up having a wider impact than people initially expected. 

Luke:
Background crap
introduces wider impact


Me:

When a strike like this happens, its easy to think that the people on strike are the only ones not working.
There are a ton of other jobs that rely on film productions, and other things that writers drive the production for.
As shows and movies stop or get delayed, this affects electricians, caterers, set dressers, directors, and a bunch of other peripheral roles.

Local businesses in towns like Hollywood, that depend on movies, tv shows, and other productions for their economy, have seen significantly less business because of the strike (As writers stop working, production slows down and people stop getting paid. Thus, less money to spend at local businesses.).

As these industries start to feel the effect of the strike, a lot of people have voiced concerns over the length of the strike.
So far, there haven't been any noticeable negotioations over ending the strike, but we may also see a much more significant impact in the next few months.

So far, studios have been able to produce and release material that had been written before the strike began - that's why we've continued to see episodes and movies release during the strike. Now however, they are running out of this "pre-written" material.

We don't know how that will affect the entertainment industry, but it seems obvious that if the writer (and actors?) dont go back to work soon, theres going to be a significant impact on a lot of different people. 
