#+TITLE: Coastal Sail Reflection
#+AUTHOR: 2/c Christian Johnson
#+LATEX_CLASS: article
#+latex_class_options: [12pt]
#+options: toc:nil num:nil title:nil
#+LATEX: \setlength\parindent{0pt}


* Coastal Sail Reflection
2/c Christian Johnson

Thursday, 13 July 2023

** Individual
In general, I am an extremely introverted person. I struggle to interact with others for extended periods of time, and I dislike taking charge of an evolution unless I know the people involved very well. I am typically not an assertive person, and even if I know the best way to approach an issue or answer a question, I typically prefer to wait until prompted to provide the answer - watching from the rear of a group to see how others approach a situation, or trying to determine the most effective way to solve a problem. My work ethic typically revolves around identifying a problem, recognizing how others have approached that problem, and then either solving it myself (alone) or gently suggesting better methods to people who are more capable than I am (when I can't solve a problem myself). As such, I sought to step outside my comfort zone during this trip. I looked for opportunities to engage others, despite the fact that I am not comfortable with, nor am I particularly good at, being social. I made a concerted effort to, instead of mentally noting when something was being done incorrectly, remedy the situation and teach others how to do better. I sought to voluntarily direct at least one evolution outside of my assigned leadership roles, and I looked for chances to practice solving problems as a group, rather than my typical "fix or delegate" approach.  

Over the course of the week, most of my goals changed - by the fifth day underway, my primary goal was to be as outgoing as possible and as productive as possible while still remaining on good terms with everyone on the boat. By and large this was easy; two of my shipmates were my friends, 3 were extremely quiet, and 1 was generally cheerful. Having never had siblings, and always having found a way to establish strong boundaries with my roommates however, I have never had to live in such close quarters with other people before. I am an extremely private person, and I am relatively neat. I struggle when other people either don't respect my personal space, or don't respect the sanctity of a shared public space. As such, the biggest challenge for me on this trip was dealing with other peoples' lack of awareness or general disregard for their surroundings - putting dirty dishes on the drying rack (which clearly had clean, drying dishes on it), leaving foulies lying on the table for extended periods, leaving towels drying on deck when we are trying to get underway. Trivial as they may be, these small things were made it most difficult to remain civil over the course of the trip, and this is what I struggled with most.

Because my goals shifted somewhat, it's difficult to say how well I did at achieving them. I would say that for the first few days, I was solidly on track to either achieve or make solid progress on my goals. After I changed my mindset to accommodate other people, I would say I did relatively well overall, but slipped in several situations where I let my irritation get the better of me.

The feedback I received from my peers was helpful - it helped me to identify aspects of what I had done during coastal sail that "worked" in a team environment, and what didn't. The people who knew me already gave very different feedback from the people who didn't already know me, which will help me in how I approach team relationships going forward. There are things that work well only if it's within a group I know already, and there are things that work better in a group with whom I'm starting fresh. 

** Team
My team goals for this program were extremely similar to my individual goals. Prior to beginning the program, I thought that we should aim to optimize efficiency and improve communication. After realizing how confined our quarters were and the type of environment we would be working in, I realized that these might be somewhat too optimistic, and instead made it a priority to respect the assigned roles for the day and work as a group to communicate about what the task at hand involved. I think we all went through similar realizations, and all came to the conclusion that working together and focusing on highlighting the day's leadership team was one of the more important aspects of our team development. We all worked very well at encouraging the watch captain, and I know I spent a fair amount of time each night showing the navigators after me how to use the GPS system (other people filled similar roles with the other positions). While we did have some small disagreements, such as a navigator and a watch captain differing on the best route to take around a buoy, most interactions were markedly civil. This continued for most of the trip, with the longest and roughest day being the tensest, likely because of these factors. In the future, building effective teams can, at a base level at least, be reduced to identifying a clear task, deciding upon roles among the group, and identifying a path to accomplishing the task. 

** Larger Context
Within a team setting, individuals can have several roles. In order to be successful, almost all teams must have a leader or leaders, with the rest being followers. A leader must guide the team to a successful outcome, delegating responsibilities and roles as they see fit, and a follower must do their best to accomplish that goal within the leaders' assigned guidelines. This is obviously a rather loose designation for individual roles within a team, but it seems to be the base requirement for a team to function. To truly succeed however, the followers must actively engage in the situation, suggesting solutions to the leader, taking initiative, and adopting responsibility themselves. Personally, as I mentioned previously, I struggle to engage with the people around me and I want to improve on my ability to work in a team. Typically I either take all the responsibility upon myself, or find ways to foist what I cannot do on others. I would like to make this a more collaborative process instead of trying to solve everything myself. If I did Coastal Sail over again, I think I would like to focus less on being outgoing, since that isn't really my typical personality. Focusing more on selective engagement and momentary energy may be more effective; both for my personal longevity in team environments and for the overall productivity and success of the group. 
